# .github/workflows/ci-cd.yml
name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'

      - name: Build with Maven
        run: ./mvnw package

      - name: Build Docker image
        run: docker build -t my-spring-boot-app .

      - name: Log in to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push image to ECR
        env:
          ECR_REGISTRY: <your-ecr-registry>
          ECR_REPOSITORY: my-spring-boot-app
          IMAGE_TAG: latest
        run: |
          docker tag my-spring-boot-app:latest $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Trigger deployment to AWS
        run: |
          aws ecs update-service --cluster <your-cluster> --service <your-service> --force-new-deployment
